version: "3.3"

services:
  jasperdog:
    image: jasperdog:latest
    networks:
     - web
    secrets:
     - slack-signing-secret
     - slack-client-id
     - slack-client-secret
    deploy:
      labels:
        - "traefik.enable=true" # <== Enable traefik to proxy this container
        - "traefik.http.routers.jasper-secured.rule=Host(`jasperdog.newlinkedlist.xyz`)"
        - "traefik.http.routers.jasper-secured.entrypoints=web-secured" # <== Defining entrypoint for https, **ref: line 31
        - "traefik.http.routers.jasper-secured.tls=true"
        - "traefik.http.services.jasper.loadbalancer.server.port=8080"
        - "traefik.http.middlewares.test-ratelimit.ratelimit.average=6"
        - "traefik.http.middlewares.test-ratelimit.ratelimit.period=1m"
networks:
  web:
    external: true

secrets:
  slack-signing-secret:
    external: true
  slack-client-id:
    external: true
  slack-client-secret:
    external: true
